name: Go Release and Test

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Run Tests
        run: go test -v


  release:
    name: Create Release
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history of semantic versioning

      - name: Install Go Semantic Release
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/go-semantic-release/semantic-release/releases/latest | jq -r '.tag_name')
          FILENAME="semantic-release_${LATEST_VERSION#v}_linux_amd64"
          curl -sL https://github.com/go-semantic-release/semantic-release/releases/download/$LATEST_VERSION/$FILENAME -o semantic-release
          chmod +x semantic-release
          sudo mv semantic-release /usr/local/bin/

      - name: Run Go Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release

