name: Go Release and Test

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Tests
        run: go test -v


  release:
    name: Create Release
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history of semantic versioning

      - name: Setup Node.js (for semantic-release)
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Semantic Release
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release

