name: Go Release and Test

on:
    push:
        branches:
            - master
    pull_request:
        types:
            - closed

jobs:
    test:
        name: Run Go Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.24

            - name: Run Tests
              run: go test -v

    release:
        name: Create Release
        needs: test
        runs-on: ubuntu-latest
        permissions:
            contents: write # Required to create release

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Fetch full history of semantic versioning

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18 # Use the latest stable version

            - name: Install Semantic Release
              run: npm install -g semantic-release @semantic-release/github @semantic-release/changelog

            - name: Run Semantic Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for creating releases
              run: semantic-release
